### ISSUE TITLE
Add obj folder to .gitignore

### ISSUE THREAD

**Issue by vishalbiswas** [andymanic/PresentMonLauncher#1]
Include a `.gitignore` and add obj to it for a cleaner repo?

**Comment by andymanic** [comment]
You are right, added it now and will remove the obj files in a sec!

**Comment by vishalbiswas** [comment]
Why do we still have bin and obj folders in the repo?

**Comment by andymanic** [comment]
H0rnman's fork of this included them and switched the .gitignore files. I'm going to delete them now and re-add that to the .gitignore
