### ISSUE TITLE
Implement global hotkey

### ISSUE THREAD

**Issue by h0rnman** [andymanic/PresentMonLauncher#17]
Implement a global hotkey to activate data collection.  Workflow would be:
1.  Launch Game
2.  Launch PresentmonLauncher
3.  Select process
4.  Switch back to game and use hotkey to begin recording

We might also want to tie this into the game autodetection feature.  If we can get a central process list to search against, we might have PresentmonLauncher automatically select the process when it starts up if it finds an active process that matches in the list.  This way, we could cut out step 3, and I feel like that would be a more pleasant user experience.

**Comment by andymanic** [comment]
Added
