### ISSUE TITLE
Add charting module to BencherWindow

### ISSUE THREAD

**Issue by h0rnman** [andymanic/PresentMonLauncher#4]
The code I submitted for the charting module needs to be merged into the main codebase.  Adding as an enhancement so that someone can be assigned to work on it.  It doesn't matter who does it, but I don't want all three of us trying to do it at once.

**Comment by andymanic** [comment]
While there is still room for improvement on this, I'm going to close this one as the actual feature has been implemented and now onto updates/bugfixes/revisions.
