### ISSUE TITLE
Redesign Main Window UI

### ISSUE THREAD

**Issue by h0rnman** [andymanic/PresentMonLauncher#6]
The current UI is a bit of a mess.  Attached PNG of proposed interface changes.
![proposed ui](https://cloud.githubusercontent.com/assets/1656321/17600398/f008c0c2-5fc8-11e6-9503-2f51f6653ad4.png)

**Comment by h0rnman** [comment]
Additionally, the "?" box next to Output File would bring up a dialog with the CSV Column Explanations text.

**Comment by andymanic** [comment]
This has been done. Only thing left is to do the CSV explanations as I've currently got it to just explain why you might want to change the output file name along with the ETL file. Going to mark as closed since I'm adding the CSV explanations now but otherwise done and checked for bugs.
